name: build-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        run: nuget restore ".\ProjekatAndjelaStankovic.sln"
      - name: Build solution (Release)
        run: msbuild ".\ProjekatAndjelaStankovic.sln" /p:Configuration=Release /m

      - name: Setup .NET SDK (for tests)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run tests (xUnit)
        run: dotnet test ".\Invoice.Tests\Invoice.Tests.csproj" --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"