name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    env:
      CONFIGURATION: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        run: nuget restore ".\ProjekatAndjelaStankovic.sln"
      - name: Build solution (Release)
        run: msbuild ".\ProjekatAndjelaStankovic.sln" /m /p:Configuration=${{ env.CONFIGURATION }} /p:Platform="Any CPU"

      - name: Setup .NET SDK (for tests)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run tests (xUnit)
        run: dotnet test --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal
